language: scala
scala:
  - 2.12.8
  - 2.11.12
  - 2.10.7
jdk:
  - oraclejdk8
  - openjdk11
script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport && sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls
